services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      default:
  devopsmetrics:
    image: local/devops-metrics:latest
    ports:
      - "8080:80" 
    env_file:
      - ./env/devopsmetrics.env